services:
  # PostgreSQL Database
  postgres:
    image: postgres:13
    container_name: wix-products-catalog-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wix-catalog-network

  # Backend - Nest.js
  backend:
    build:
      context: ./backend
    container_name: wix-products-catalog-backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - wix-catalog-network

  # Frontend - Vue.js
  frontend:
    build:
      context: ./frontend
    container_name: wix-products-catalog-frontend
    env_file:
      - ./backend/.env
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - wix-catalog-network

volumes:
  postgres_data:

networks:
  wix-catalog-network:
    driver: bridge