services:
  postgres:
    image: postgres:13
    container_name: wix-products-catalog-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wix-catalog-network
    env_file:
      - ./backend/.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: wix-products-catalog-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    networks:
      - wix-catalog-network
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: wix-products-catalog-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - wix-catalog-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./frontend/.env

volumes:
  postgres_data:

networks:
  wix-catalog-network:
    driver: bridge