version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:13
    container_name: wix-products-catalog-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend - Nest.js
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: wix-products-catalog-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres

  # Frontend - Vue.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: wix-products-catalog-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data: