version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend - Nest.js
  backend:
    build:
      context: ./backend
    container_name: nestjs_app
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      WIX_API_URL: ${WIX_API_URL}
      WIX_API_KEY: ${WIX_API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  # Frontend - Vue.js
  frontend:
    build:
      context: ./frontend
    container_name: vue_app
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data: