version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend - Nest.js
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  # Frontend - Vue.js
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data: