# Use node official image as base
FROM node:18-alpine

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install
# Optional: Install the nest-cli globally
RUN npm install -g @nestjs/cli

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Start the application in development mode with hot-reloading
CMD ["npm", "run", "start:dev"]